baseURL: "https://literallytheone.github.io"
languageCode: "en-us"
title: "LiterallyTheOne"

caches:
  images:
    dir: ":cacheDir/images"

menus:
  main:
    - name: "About Me"
      pageRef: "/about"
      weight: 10
    - name: "Posts"
      pageRef: "/posts"
      weight: 20
    - name: "Tags"
      pageRef: "/tags"
      weight: 30
    - name: "Tutorials"
      pageRef: "/tutorials"
      weight: 40

pagination:
  pagerSize: 6

outputFormats:
  PANDOC:
    mediaType: text/html
    baseName: pandoc
    isHTML: true
    rel: alternate

outputs:
  home:
    - HTML
    - JSON
  section:
    - HTML
    - PANDOC
  page:
    - HTML
    - PANDOC
