baseURL = 'https://literallytheone.github.io'
languageCode = 'en-us'
title = 'LiterallyTheOne'

[caches]
[caches.images]
dir = ':cacheDir/images'

[[menus.main]]
name = 'About Me'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30


[[menus.main]]
name = 'Tutorials'
pageRef = '/tutorials'
weight = 40



[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[pagination]
pagerSize = 6


[outputs]
home = ["HTML", "JSON"]