baseURL = 'https://literallytheone.github.io'
languageCode = 'en-us'
title = 'LiterallyTheOne'

[caches]
[caches.images]
dir = ':cacheDir/images'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
